version: '3'
services:
  backend:
   build:
     context: ./backend
     dockerfile: Dockerfile
   volumes:
     - ./backend:/home/app/docker_money
   ports:
     - '3000:3000'
   tty: true
   depends_on:
     - mongodb
  mongodb:
    image: mongo:3.4.10
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    volumes:
      - ./frontend:/home/app/docker_money
